version: "3.9"

services:
  nextjs-grpc-infra:
    container_name: nextjs-grpc-infra
    image: utkusarioglu/tf-devcontainer:1.2.18
    environment:
      TZ: Etc/UTC0
    extra_hosts:
      infra.nextjs-grpc.projects.utkusarioglu.com: host-gateway
    volumes:
      - type: bind
        source: ..
        target: /utkusarioglu-com/projects/nextjs-grpc/infra
