version: "3.9"

services:
  nextjs-grpc-infra:
    environment:
      HOST_VOLUMES_ROOT: ${HOME}/volumes/nextjs-grpc
      HOST_SOURCE_CODE_ROOT: ${HOME}/dev/projects/nextjs-grpc
      VAULT_ADDR: https://vault.nextjs-grpc.utkusarioglu.com:8200
      CLUSTER_HOST: local.dev.k3d.nextjs-grpc.projects.utkusarioglu.com
    extra_hosts:
      host-gateway: host-gateway
