name: Push

on:
  push:
    tags:
      - "**.**.**"
      - "experiment/**/**/**"
    # paths:
    #   - src/**
    #   - .github/workflows/push.yml
    #   - .github/workflows/k3d-dev-local.integration.test.wfc.yml
    #   - .github/workflows/k3d-dev-local.e2e.test.wfc.yml
  workflow_dispatch:

jobs:
  k3d-dev-local-integration-test:
    uses: ./.github/workflows/k3d-dev-local.integration.test.wfc.yml
    secrets: inherit
    with:
      infraRef: ${{ github.ref_name }}
      # frontendRef: experiment/test/workflow-calls
      # msRef: experiment/chore/workflow-call

  # k3d-dev-local-e2e-test:
  #   uses: ./.github/workflows/k3d-dev-local.e2e.test.wfc.yml
  #   secrets: inherit
  #   with:
  #     infraRef: ${{ github.ref_name }}
