name: Test K3d Dev Local
on:
  push:
    tags:
      - "**.**.**"
      - "experiment/**/**/**"
    paths:
      - src/**
      - .github/workflows/test-k3d-dev-local.yml
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - main
  workflow_dispatch:

jobs:
  infra-test-web:
    name: infra-test-web
    uses: ./.github/workflows/test-k3d-dev-local-call.yml
    secrets: inherit
    with:
      infra: main
      frontend: main
